#å¼?å‘ç¯å¢ƒé…ç½?
server:
  #ç«¯å£
  port: 8880
  tomcat:
    uri-encoding: utf-8
#æ—¥å¿—é…ç½®
logging:
  level:
    com.yj.oa.project.mapper: debug
#æ•°æ®æº?
spring:
  datasource:
    url: jdbc:mysql://47.105.195.27:3306/sj_base?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: gaojun_123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver


# MyBatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.sj.oa.project.po
  configuration:
    map-underscore-to-camel-case: true



